=== Yoldark34/NemoVelo/src/controller/config/config.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
		An example how to use this DTD from your XML document:

		<?xml version="1.0"?>

		<!DOCTYPE config SYSTEM "config.dtd">

		<config>
		...
		</config>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT config (section)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT section (param)*>
<!ATTLIST section
	name ID #REQUIRED
>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT param EMPTY>
<!ATTLIST param
		value CDATA #REQUIRED
		name CDATA #REQUIRED
>

=== Yoldark34/NemoVelo/rsrc/resource/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "config.dtd">
<config>
	<section name="db">
		<param name="url" value="jdbc:mysql://localhost:3306/nemovelo" />
		<param name="user" value="root" />
		<param name="password" value="" />
	</section>
	<section name="log">
		<param name="unique" value="true" />
	</section>
	<section name="gui">
		<param name="cloned" value="false" />
	</section>
</config>
